title: Karen's Website
author: Grumpy Person (Karen)
email: notarealemail908230@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   
theme: minima

# social links
twitter_username: notreal9182
github_username: fake120932

show_excerpts: false
